package controllers.visualization;

import use_cases.visualization.visualization_week.VisualizationWeekInteractor;
import use_cases.visualization.visualization_week.VisualizationWeekResponseModel;
import use_cases.visualization.visualization_year.VisualizationYearOutputBoundary;

public class VisualizationYearPresenter implements VisualizationYearOutputBoundary {


}
